books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

catalog/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    # Book
    path('', BookList.as_view(), name='book-list'),
    path('book-add/', BookCreate.as_view(), name='book-create'),
    path('book-edit/<int:pk>/', BookUpdate.as_view(), name='book-update'),
    path('book-remove/<int:pk>/', BookDelete.as_view(), name='book-delete'),
    # Author
    path('author-list/', AuthorList.as_view(), name='author-list'),
    path('author-add/', AuthorCreate.as_view(), name='author-create'),
    path('author-edit/<int:pk>/', AuthorUpdate.as_view(), name='author-update'),
    path('author-remove/<int:pk>/', AuthorDelete.as_view(), name='author-delete'),
    # Google Api Views
    path('google-books-search/', google_search, name='google-search'),
    path('google-books-search/change-books-per-page/', change_books_per_page),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.conf.global_settings import LANGUAGES
from django.utils.text import slugify


class Author(models.Model):
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.last_name + ' ' + self.first_name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class Book(models.Model):
    title = models.CharField(max_length=200)
    authors = models.ManyToManyField(Author)
    publication_date = models.DateField(null=True, blank=True)
    isbn = models.CharField(max_length=13, help_text='13 Character ISBN number', null=True, blank=True)
    number_of_pages = models.IntegerField(null=True, blank=True)
    cover = models.URLField(null=True, blank=True)
    language = models.CharField(max_length=7, choices=LANGUAGES, null=True, blank=True)

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('book-detail', args=self.isbn)

    def __str__(self):
        return f'{self.title} - {self.author}'

catalog/forms.py
from django import forms
from django.utils.text import slugify
from django.conf.global_settings import LANGUAGES

from .models import Author, Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = '__all__'
        widgets = {'publication_date': forms.widgets.DateInput(attrs={'type': 'date'})}


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        exclude = ['slug']
        widgets = {'date_of_birth': forms.widgets.DateInput(attrs={'type': 'date'}),
                   'date_of_death': forms.widgets.DateInput(attrs={'type': 'date'})}

    def clean(self, *args, **kwargs):
        # Is new author unique?
        cleaned_data = super(AuthorForm, self).clean(*args, **kwargs)
        name = cleaned_data.get('first_name')
        surname = cleaned_data.get('last_name')
        if name and surname:
            slug = slugify(surname + ' ' + name)
            qs = Author.objects.filter(slug=slug).exists()
            if qs:
                raise forms.ValidationError("Autor już istnieje")
        return cleaned_data


lang = LANGUAGES.copy()
lang.insert(0, (None, '-'))


class SearchForm(forms.Form):
    title = forms.CharField(required=False, label='Tytuł')
    author = forms.CharField(required=False, label='Autor')
    language = forms.ChoiceField(choices=lang, required=False, label='Język')
    date_begin = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), required=False, label='Data od')
    date_end = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), required=False, label='Data do')


class GoogleForm(forms.Form):
    q = forms.CharField(required=False, label='Szukaj')
    intitle = forms.CharField(required=False, label='Tytuł')
    inauthor = forms.CharField(required=False, label='Autor')
    inpublisher = forms.CharField(required=False, label='Wydawnictwo')
    subject = forms.CharField(required=False, label='Tematyka')
    isbn = forms.CharField(required=False, label='ISBN')
    lccn = forms.CharField(required=False, label='LCCN')
    oclc = forms.CharField(required=False, label='OCLC')

catalog/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render

from .models import Author, Book
from .forms import BookForm, AuthorForm, SearchForm, GoogleForm

import requests


# Book Views


class BookList(ListView):

    context_object_name = 'books'
    model = Book
    paginate_by = 100
    template_name = 'catalog/book-list.html'

    def get_queryset(self):
        # Wyszukiwanie w katalogu
        title = self.request.GET.get('title')
        author = self.request.GET.get('author')
        language = self.request.GET.get('language')
        date_begin = self.request.GET.get('date_begin')
        date_end = self.request.GET.get('date_end')
        qs = Book.objects.all()
        if title:
            qs = qs.filter(title__icontains=title)
        if author:
            qs = qs.filter(Q(author__first_name__icontains=author) |
                           Q(author__last_name__icontains=author))
        if language:
            qs = qs.filter(language__icontains=language)
        if date_begin:
            qs = qs.filter(publication_date__gte=date_begin)
        if date_end:
            qs = qs.filter(publication_date__lte=date_end)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookList, self).get_context_data(**kwargs)
        context['search_form'] = SearchForm(self.request.GET or None)
        return context


class BookCreate(CreateView):

    form_class = BookForm
    template_name = 'catalog/book-add.html'
    success_url = reverse_lazy('book-list')


class BookUpdate(UpdateView):

    form_class = BookForm
    model = Book
    template_name = 'catalog/book-add.html'
    success_url = reverse_lazy('book-list')


class BookDelete(DeleteView):

    model = Book
    template_name = 'catalog/book-delete.html'
    success_url = reverse_lazy('book-list')


# Author Views


class AuthorList(ListView):

    context_object_name = 'authors'
    model = Author
    paginate_by = 100
    template_name = 'catalog/author-list.html'


class AuthorCreate(CreateView):

    form_class = AuthorForm
    template_name = 'catalog/book-add.html'
    success_url = reverse_lazy('author-list')


class AuthorUpdate(UpdateView):

    form_class = AuthorForm
    model = Author
    template_name = 'catalog/book-add.html'
    success_url = reverse_lazy('author-list')


class AuthorDelete(DeleteView):

    model = Author
    template_name = 'catalog/book-delete.html'
    success_url = reverse_lazy('auhtor-list')


# Google Api Views


def google_search(request):
    temlpate_name = 'catalog/google-search.html'
    form = GoogleForm(request.POST or None)
    context = {'form': form}

    if form.is_valid() and form.is_bound:
        # request.session['google_form'] = form
        if not request.session.get('books_per_page'):
            request.session['books_per_page'] = 12
        count = request.session['books_per_page']
        start = request.GET.get('start', 0)
        url = make_url(form, count, start)
        response = requests.get(url)
        book_data = response.json()
        books = book_data['items']
        count_books = book_data['totalItems']
        context.update({'books': books, 'count_books': count_books})
    return render(request, temlpate_name, context=context)

def make_url(form, count, start):
    url = 'https://www.googleapis.com/books/v1/volumes'
    url += '?q=' + form.cleaned_data['q']
    for key, value in form.cleaned_data.items():
        if value != '' and key != 'q':
            url += '+' + key + ':' + value
    url += '&maxResults=' + str(count) + '&startIndex=' + str(start)
    return url

# def download_books(url):
#     response = requests.get(url)
#     book_data = response.json()
#     count_books = book_data['totalItems']
#     x = 40 
#     while x < count_books:
#         api = url + '&startIndex=' + str(x)
#         print(api)
#         response = requests.get(api)
#         data = response.json()
#         book_data.update(data)
#         x += 40
#     return book_data['items'], count_books

def change_books_per_page(request):
    if request.GET.get('bpp'):
        request.session['books_per_page'] = request.GET.get('bpp')
    return JsonResponse({})

catalog/templates/catalog/author-list.html
{% extends 'skeleton.html' %}

{% block title %}
    List of autors
{% endblock %}


{% block content %}

{% for author in authors %}
    <p>{{ author.first_name }} {{ author.last_name }}</p>
{% endfor %}

{% endblock %}

catalog/templates/catalog/book-add.html
{% extends 'skeleton.html' %}

{% block title %}
    Add book
{% endblock %}

{% block content %}

{% load widget_tweaks %}

<form method="post" novalidate>
    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% for error in form.non_field_errors %}
        <p class="help is-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form.visible_fields %}
    <div class="field">
        <label class="label">{{ field.label_tag }}</label>
        {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
        {% endfor %}
        <div class="control">
            {% if field.name == 'authors' %}
            <div class="select is-multiple">
                {% render_field field size="8" %}
            </div>
            {% elif field.name == 'language' %}
            <div class="select">
                {% render_field field %}
            </div>
            {% else %}
            {% render_field field class="input" %}
            {% endif %}
        </div>
        {% if field.help_text %}
            <p class="help">{{ field.help_text }}</p>
        {% endif %}
    </div>
    {% endfor %}

    <div class="field is-grouped">
        <div class="control">
            <button type="submit" class="button is-link">Zapisz</button>
        </div>
        <div class="control">
            <input type="button" class="button is-link is-light" value="Anuluj" onclick="window.location.href = {% url 'book-list' %};">
        </div>
    </div>

</form>

{% endblock %}

catalog/templates/catalog/book-delete.html
<form method="post">{% csrf_token %}
    <p>Czy na pewno chcesz usunąć "{{ object }}"?</p>
    <input type="submit" value="Tak">
    <input type="button" value="Nie" onclick="window.location.href = {% url 'book-list' %};">
</form>

catalog/templates/catalog/book-list.html
{% extends 'skeleton.html' %}
{% load i18n %}

{% block title %}
Book list
{% endblock %}


{% block content %}

<div class="columns is-multiline">
	{% for book in books %}
	<div class="column is-12-mobile is-6-tablet is-4-desktop is-3-widescreen is-3-fullhd">

		<div class="card">
			<div class="card-image" style="background-image: url({{ book.cover }}); background-size:cover;"></div>

			<div class="card-content">
				<h5 class="title is-6">{{ book.title|truncatechars:70 }}</h5>
				{% for author in book.authors.all %}
				<h6 class="subtitle is-6">{{ author }}</h6>
				{% endfor %}

				{% if book.publication_date %}<div>Data publikacji: {{ book.publication_date }}</div>{% endif %}
				{% if book.isbn %}<div>ISBN: {{ book.isbn }}</div>{% endif %}
				{% if book.number_of_pages %}<div>Liczba stron: {{ book.number_of_pages }}</div>{% endif %}
				{% if book.get_language_display %}<div>Język: {{ book.get_language_display }}</div>{% endif %}
			</div>

			<footer class="card-footer">
				<a href="{% url 'book-update' book.pk %}" class="card-footer-item">Edytuj</a>
				<a href="{% url 'book-delete' book.pk %}" class="card-footer-item">Usuń</a>
			</footer>
		</div>

	</div>

	{% empty %}
	<div><p>No books yet.</p></div>
	{% endfor %}
	
</div>

{% endblock %}

catalog/templates/catalog/google-search.html
{% extends 'skeleton.html' %}

{% block content %}

{% load widget_tweaks %}

{% if books %}
<div class="notification is-success">
  <button class="delete"></button>
  <p>Znaleziono {{ count_books }} książek <p>
</div>
{% endif %}

<form method="post" novalidate>
  {% csrf_token %}
  <div class="columns is-multiline">

    <div class="column is-12">
      <div class="field">
        <label class="label">{{ form.q.label_tag }}</label>
        <div class="control">
          {% render_field form.q class="input is-large" %}
        </div>
      </div>
    </div>
<!--<div class="column is-12">
      <a id="advanced-search-toggle" class="is-link is-small">Wyszukiwanie zaawansowane</a>
    </div> -->
    <div id="advanced-search" class="column is-12">
      <div class="columns is-multiline">
        {% for field in form.visible_fields %}
        {% if field.name == 'q' %}
        {% else %}

        <div class="column is-12-mobile is-6-tablet is-4-desktop is-3-widescreen is-2-fullhd">
          <div class="field">
            <label class="label">{{ field.label_tag }}</label>
            <div class="control">
              {% render_field field class="input" %}
            </div>
            {% if field.help_text %}
            <p class="help">{{ field.help_text }}</p>
            {% endif %}
          </div>
        </div>

        {% endif %}
        {% endfor %}
      </div>
    </div>

    <div class="column is-12-mobile is-6-tablet is-4-desktop is-3-widescreen is-2-fullhd">
      <div class="control">
        <button type="submit" class="button is-link">Szukaj</button>
      </div>
    </div>

  </div>

</form>


{% if books %}

<div class="columns is-multiline">
  <div class="column is-12-mobile is-2-tablet">
    <div class="select">
      <select id="books_per_page">
        <option value='12' {% if request.session.books_per_page == '12' %}selected{% endif %}>12</option>
        <option value='24' {% if request.session.books_per_page == '24' %}selected{% endif %}>24</option>
        <option value='40' {% if request.session.books_per_page == '40' %}selected{% endif %}>40</option>
      </select>
    </div>
  </div>
</div>
{{ request.session.books_per_page }}
<div class="columns is-multiline">

  {% for book in books %}
  <div class="column is-12-mobile is-6-tablet is-4-desktop is-3-widescreen is-2-fullhd">

    <div class="card">
      <div class="card-image" style="background-image: url({{ book.volumeInfo.imageLinks.thumbnail }}); background-size:cover;"></div>

      <div class="card-content">
        <h5 class="title is-6">{{ book.volumeInfo.title|truncatechars:70 }}</h5>
        {% for author in book.volumeInfo.authors %}
        <h6 class="subtitle is-6">{{ author }}</h6>
        {% endfor %}

        <div>Data publikacji: {{ book.volumeInfo.publishedDate }}</div>
        <div>ISBN: {{ book.volumeInfo.industryIdentifiers.1.identifier }}</div>
        <div>Liczba stron: {{ book.volumeInfo.pageCount }}</div>
        <div>Język: {{ book.volumeInfo.language }}</div>
      </div>

    </div>

  </div>

  {% endfor %}

</div>

{% endif %}


<nav class="pagination" role="navigation" aria-label="pagination">
  <a class="pagination-previous">Previous</a>
  <a class="pagination-next">Next page</a>
  {% if books.has_other_pages %}
  <ul class="pagination-list">
    {% if books.has_previous %}
      <li><a class="pagination-link" href="#">&laquo;</a></li>
    {% else %}
      <li><span>&laquo;</span></li>
    {% endif %}

    {% for i in books.paginator.page_range %}
      {% if books.number == i %}
        <li class="pagination-link is-current"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a class="pagination-link" href="#">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if books.has_next %}
      <li><a class="pagination-link" href="#">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  {% endif %}
</nav>


{% endblock %}